[package]
name = "WinDoubleJoy"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = "0.11.8"
futures = "0.3.31"
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread", "macros"] }
uuid = { version = "1.20.0", features = ["v4"] }
